# Generated by Django 5.0.6 on 2024-06-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_created_date_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='term_conditions',
            field=models.BooleanField(default=False),
        ),
    ]
